name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Atau branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Selalu gunakan versi terbaru jika memungkinkan

      # Jika Anda perlu build step (misalnya, jika 'public' adalah hasil build)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20' # Ganti dengan versi Node.js Anda
      # - name: Install dependencies
      #   run: npm install
      # - name: Build static files
      #   run: npm run build # Ganti dengan perintah build Anda jika ada

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Selalu gunakan versi terbaru jika memungkinkan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Direktori yang akan di-deploy
          # publish_branch: gh-pages # Branch tujuan (defaultnya gh-pages)
          # cname: your.custom.domain.com # Jika Anda menggunakan custom domain
